naturalistic_speech:
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - Slow Barcode
  - TENS
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
  - leftCamTripod
  - rightCamTripod
n_back:
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - Slow Barcode
  - TENS
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
  - leftCamTripod
  - rightCamTripod
motor_task_finger_taps:
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - Slow Barcode
  - TENS
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
  - leftCamTripod
  - rightCamTripod
diadochokinesis:
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - Slow Barcode
  - TENS
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
  - leftCamTripod
  - rightCamTripod
verbal_fluency:
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
  - leftCamTripod
  - rightCamTripod
vowel_space:
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
  - leftCamTripod
  - rightCamTripod
reach_grasp:
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Grasp Button
  - Microphone 1
  - Microphone 2
  - Force Sensor X
  - Force Sensor Y
  - Force Sensor Z
  - Barcode
  - Slow Barcode
  - TENS
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
  - leftCamTripod
  - rightCamTripod
tone_taps_closed:
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
  - leftCamTripod
  - rightCamTripod
sara:
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
  - leftCamTripod
  - rightCamTripod
verb_generation:
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
  - leftCamTripod
  - rightCamTripod

continuous_recording:
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Grasp Button
  - Microphone 1
  - Microphone 2
  - Force Sensor X
  - Force Sensor Y
  - Force Sensor Z
  - Barcode
  - Slow Barcode
  - TENS
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
  - leftCamTripod
  - rightCamTripod